// ========================================
// Maestro Besar — Bahasa Indonesia (id)
// Struktur i18n · 9 baris 2 paragraf
// v70 - 2026-02-03
// ========================================

export const mastersBasicInfo = {
  'vangogh': { loading: { name: 'Vincent van Gogh (1853–1890)', subtitle1: 'Malam Berbintang · Bunga Matahari · Potret Diri', subtitle2: 'Gairah kuas yang berputar spiral' } },
  'klimt': { loading: { name: 'Gustav Klimt (1862–1918)', subtitle1: 'Ciuman · Judith · Pohon Kehidupan', subtitle2: 'Dunia emas penuh sensualitas' } },
  'munch': { loading: { name: 'Edvard Munch (1863–1944)', subtitle1: 'Jeritan · Madonna · Pubertas', subtitle2: 'Melukis jeritan batin' } },
  'matisse': { loading: { name: 'Henri Matisse (1869–1954)', subtitle1: 'Tarian · Kamar Merah · Wanita Bertopi', subtitle2: 'Pesulap warna' } },
  'chagall': { loading: { name: 'Marc Chagall (1887–1985)', subtitle1: 'Di Atas Kota · Aku dan Desa · Buket dengan Kekasih Terbang', subtitle2: 'Penyair cinta dan mimpi' } },
  'picasso': { loading: { name: 'Pablo Picasso (1881–1973)', subtitle1: 'Les Demoiselles d\'Avignon · Guernica · Potret Dora Maar', subtitle2: 'Revolusioner yang mendekonstruksi pandangan' } },
  'frida': { loading: { name: 'Frida Kahlo (1907–1954)', subtitle1: 'Kolom Patah · Potret Diri dengan Kalung Duri dan Kolibri', subtitle2: 'Potret diri yang menghadapi rasa sakit' } },
  'lichtenstein': { loading: { name: 'Roy Lichtenstein (1923–1997)', subtitle1: 'Drowning Girl · Whaam! · In the Car', subtitle2: 'Pria yang mengubah komik menjadi seni' } },

  'vangogh-starry': { result: { name: 'Vincent van Gogh (1853–1890)', subtitle1: 'Malam Berbintang (The Starry Night)', subtitle2: 'Cemara dan bintang dalam spiral' } },
  'vangogh-sunflower': { result: { name: 'Vincent van Gogh (1853–1890)', subtitle1: 'Bunga Matahari (Sunflowers)', subtitle2: 'Lima belas matahari dalam vas' } },
  'vangogh-selfportrait': { result: { name: 'Vincent van Gogh (1853–1890)', subtitle1: 'Potret Diri (Self-Portrait)', subtitle2: 'Tatapan paling jujur di dunia' } },
  'klimt-kiss': { result: { name: 'Gustav Klimt (1862–1918)', subtitle1: 'Ciuman (The Kiss)', subtitle2: 'Cinta terbalut emas' } },
  'klimt-judith': { result: { name: 'Gustav Klimt (1862–1918)', subtitle1: 'Judith I (Judith I)', subtitle2: 'Rayuan dan kekuasaan' } },
  'klimt-treeoflife': { result: { name: 'Gustav Klimt (1862–1918)', subtitle1: 'Pohon Kehidupan (The Tree of Life)', subtitle2: 'Spiral keabadian' } },
  'munch-scream': { result: { name: 'Edvard Munch (1863–1944)', subtitle1: 'Jeritan (The Scream)', subtitle2: 'Kecemasan yang menjadi gambar' } },
  'munch-madonna': { result: { name: 'Edvard Munch (1863–1944)', subtitle1: 'Madonna (Madonna)', subtitle2: 'Di mana kesucian dan sensualitas bertemu' } },
  'munch-puberty': { result: { name: 'Edvard Munch (1863–1944)', subtitle1: 'Pubertas (Puberty)', subtitle2: 'Kegelisahan kepolosan' } },
  'matisse-dance': { result: { name: 'Henri Matisse (1869–1954)', subtitle1: 'Tarian (The Dance)', subtitle2: 'Ritme primordial tubuh' } },
  'matisse-redroom': { result: { name: 'Henri Matisse (1869–1954)', subtitle1: 'Kamar Merah (The Red Room)', subtitle2: 'Dunia yang digenangi merah' } },
  'matisse-hat': { result: { name: 'Henri Matisse (1869–1954)', subtitle1: 'Wanita Bertopi (Woman with a Hat)', subtitle2: 'Tembakan pembuka Fauvisme' } },
  'chagall-overthecity': { result: { name: 'Marc Chagall (1887–1985)', subtitle1: 'Di Atas Kota (Over the Town)', subtitle2: 'Terbang di atas kota bersama kekasih' } },
  'chagall-iandthevillage': { result: { name: 'Marc Chagall (1887–1985)', subtitle1: 'Aku dan Desa (I and the Village)', subtitle2: 'Nostalgia kampung halaman dalam mimpi' } },
  'chagall-bouquet': { result: { name: 'Marc Chagall (1887–1985)', subtitle1: 'Buket dengan Kekasih Terbang (Bouquet with Flying Lovers)', subtitle2: 'Bunga yang mekar dalam cinta' } },
  'picasso-demoiselles': { result: { name: 'Pablo Picasso (1881–1973)', subtitle1: 'Les Demoiselles d\'Avignon (Les Demoiselles d\'Avignon)', subtitle2: 'Detonasi Kubisme' } },
  'picasso-guernica': { result: { name: 'Pablo Picasso (1881–1973)', subtitle1: 'Guernica (Guernica)', subtitle2: 'Jeritan menentang perang' } },
  'picasso-doramaar': { result: { name: 'Pablo Picasso (1881–1973)', subtitle1: 'Potret Dora Maar (Portrait of Dora Maar)', subtitle2: 'Depan dan samping dalam satu wajah' } },
  'frida-brokencolumn': { result: { name: 'Frida Kahlo (1907–1954)', subtitle1: 'Kolom Patah (The Broken Column)', subtitle2: 'Tubuh terbuka, jiwa tak tergoyahkan' } },
  'frida-thornnecklace': { result: { name: 'Frida Kahlo (1907–1954)', subtitle1: 'Potret Diri dengan Kalung Duri dan Kolibri (Self-Portrait with Thorn Necklace and Hummingbird)', subtitle2: 'Rasa sakit sebagai mahkota' } },
  'frida-twofridaskahlo': { result: { name: 'Frida Kahlo (1907–1954)', subtitle1: 'Dua Frida (The Two Fridas)', subtitle2: 'Dua hati, satu Frida' } },
  'lichtenstein-drowninggirl': { result: { name: 'Roy Lichtenstein (1923–1997)', subtitle1: 'Drowning Girl (Drowning Girl)', subtitle2: 'Drama komik di atas kanvas' } },
  'lichtenstein-whaam': { result: { name: 'Roy Lichtenstein (1923–1997)', subtitle1: 'Whaam! (Whaam!)', subtitle2: 'Ledakan komik sebagai seni' } },
  'lichtenstein-inthecar': { result: { name: 'Roy Lichtenstein (1923–1997)', subtitle1: 'In the Car (In the Car)', subtitle2: 'Momen beku dari komik' } }
};

export const mastersLoadingEducation = {
  'vangogh': { description: `Ia dipecat dari galeri seni, meninggalkan studi teologi, dan ditolak sebagai misionaris.\nKehidupan Vincent van Gogh dimulai sebagai rangkaian kegagalan.\nIa memutuskan menjadi pelukis pada usia 27 tahun dan hanya hidup sepuluh tahun lagi.\n\nDalam satu dekade itu, dengan sapuan kuas penuh demam dan warna membara, ia mencurahkan batinnya ke atas kanvas.\nIa meninggalkan lebih dari 900 lukisan dan 1.100 gambar, tetapi hanya menjual satu karya semasa hidup.` },
  'klimt': { description: `Gustav Klimt adalah seniman yang melukis cinta dan kematian di atas lembaran emas.\nKarya-karya dekoratifnya memicu skandal di Wina akhir abad, tetapi ia tidak pernah menyerah.\nIa menerapkan lembaran emas asli di atas kanvas, mengintegrasikan estetika mosaik Bizantium.\n\nSensualitas feminin dan kilauan emas melebur menciptakan dunia impian.\nAnak pengukir yang menjadi pemberontak dunia seni Wina, melukis estetikanya sendiri tentang dekadensi.` },
  'munch': { description: `Ia kehilangan ibunya pada usia 5 tahun dan kakak perempuan tercintanya pada usia 14 tahun.\nBagi Edvard Munch, kematian bukanlah konsep yang jauh melainkan bayangan yang selalu hadir.\nIa mengubah kecemasan dan kesendirian itu menjadi gambar dan menciptakan bahasa artistik yang sepenuhnya baru.\n\nIa menuangkan emosi tak terlihat — ketakutan, kesendirian, kecemasan — langsung ke atas kanvas.\nSeorang pelukis yang mengubah luka seumur hidupnya menjadi seni seumur hidupnya.` },
  'matisse': { description: `Henri Matisse menemukan seni lukis saat memulihkan diri dari operasi usus buntu pada usia 20 tahun.\nIa meninggalkan studi hukum dan mendalami warna — awal yang tidak biasa bagi seorang seniman.\nDi Salon d'Automne 1905, kritik "binatang buas" menjadi nama gerakan tersebut.\n\nBahkan di tahun-tahun terakhir hidupnya, terbatas di kursi roda, ia terus berkarya dengan potongan kertas.\nSeniman yang tidak pernah berhenti berkarya, membebaskan warna dari kewajiban meniru kenyataan.` },
  'chagall': { description: `Marc Chagall lahir di Vitebsk, kota kecil di Belarus, dan di sana ia menemukan semua warna hidupnya.\nCintanya pada Bella, atap-atap desanya, kambing dan biola — semuanya terbang bersama ke kanvas.\nTidak peduli gerakan seni, ia melukis dunia mimpinya sendiri dengan kebebasan penuh.\n\nTerusir dari tanahnya oleh Revolusi Rusia, ia menjadi seorang Yahudi yang mengembara.\nPelukis nostalgia yang hidup 97 tahun melukis cinta, rumah, dan kenangan yang tak pernah padam.` },
  'picasso': { description: `Pada usia 13 tahun, Pablo Picasso menggambar lebih baik dari ayahnya, seorang guru seni.\nIa menguasai akademisme lalu menghancurkannya — provokasi dan penemuan kembali adalah inti kariernya.\nPeriode Biru, Mawar, Kubisme, Klasisisme, Surealisme — ia terus menemukan kembali dirinya.\n\nGuernica, dilukis dalam enam minggu kemarahan atas pemboman sebuah desa Basque, menjadi tuntutan anti-perang abad ke-20.\nDalam 91 tahun, ia meninggalkan lebih dari 50.000 karya; namanya identik dengan seni modern.` },
  'frida': { description: `Pada usia 18 tahun, Frida Kahlo mengalami kecelakaan bus mengerikan yang menghancurkan tulang belakang dan panggulnya.\nIa mulai melukis di tempat tidur, menatap cermin yang dipasang di langit-langit — begitulah potret diri sebagai cermin jiwa lahir.\nIa menikah dengan muralis Diego Rivera; mereka bercerai dan menikah lagi, melukiskan cinta yang penuh gairah dan penuh badai.\n\nIa menanggung 32 operasi sepanjang hidupnya, tetapi tidak pernah berhenti melukis.\nSeorang seniman yang mengubah rasa sakit menjadi identitas: "Kaki, untuk apa saya membutuhkannya, kalau saya punya sayap untuk terbang?"` },
  'lichtenstein': { description: `Pada tahun 1961, Roy Lichtenstein melukis komik Mickey Mouse dan dunia seni berguncang.\n"Apakah ini benar-benar seni?" — Pertanyaan itu menjadi jawabannya.\nIa memperbesar titik-titik Ben-Day dari komik cetak ke skala monumental dan batas antara seni dan budaya populer menghilang.\n\nBersama Warhol, ia membawa Pop Art ke garis depan seni.\nSeorang seniman yang membuktikan bahwa satu panel komik dapat mengubah sejarah seni.` }
};

export const mastersResultEducation = {
  'vangogh-starry': { description: `Spiral kosmis Malam Berbintang telah diterapkan.\nSapuan kuas spiral menyeret bintang, bulan, dan langit malam menciptakan ilusi gerakan kosmis.\n\nCemara gelap menjulang bagaikan api hitam, dan setiap bintang berdenyut dengan energinya sendiri.\nMahakarya yang Van Gogh lukis dari jendela rumah sakit jiwa Saint-Rémy, yang paling terkenal dari Pasca-Impresionisme.` },
  'vangogh-sunflower': { description: `Impasto tebal dan kuning krom Bunga Matahari telah diterapkan.\nKuning di atas kuning, cat diterapkan begitu tebal hingga memperoleh tekstur pahatan.\n\nDari mekar penuh hingga layu, vitalitas dan kemunduran diekspresikan secara bersamaan.\nLetupan kehidupan yang Van Gogh lukis sebagai hadiah sambutan untuk sahabatnya Gauguin.` },
  'vangogh-selfportrait': { description: `Sapuan kuas pendek dan latar spiral Potret Diri Van Gogh telah diterapkan.\nPalet dingin dan sapuan berputar menciptakan atmosfer ketegangan psikologis.\n\nLebih dari 35 potret diri, masing-masing cermin dari kondisi emosional yang berbeda.\nJurnal visual paling jujur dan mentah dalam sejarah seni.` },
  'klimt-kiss': { description: `Mosaik emas dan pola geometris Ciuman telah diterapkan.\nLembaran emas asli dan bentuk ornamental membungkus pasangan dalam kepompong keintiman.\n\nSpiral dan segitiga saling berkelindan, meleburkan dekorasi Bizantium dan ekstasi cinta.\nMahakarya Klimt di mana emas mengabadikan momen cinta yang kekal.` },
  'klimt-judith': { description: `Kontras emas-kulit dan tatapan menantang Judith I telah diterapkan.\nLembaran emas dan kulit telanjang berhadapan, mengekspresikan kekuasaan dan sensualitas.\n\nPahlawan wanita alkitabiah menatap penonton dengan mata setengah tertutup, memegang kepala Holofernes dengan senyum ambigu.\nKarya yang menantang tabu Wina akhir abad, meleburkan yang sakral dan yang erotis.` },
  'klimt-treeoflife': { description: `Spiral ritmis dan mosaik ornamental Pohon Kehidupan telah diterapkan.\nPohon bercabang spiral mengisi ruang dengan pola yang menyimbolkan siklus kehidupan.\n\nSpiral tak berujung, bunga, dan mata berkelindan sebagai metafora kelahiran, kehidupan, dan kematian.\nLambang filosofi kehidupan Klimt, di mana dekorasi menjadi alam semesta.` },
  'munch-scream': { description: `Langit merah bergelombang dan deformasi menyiksa Jeritan telah diterapkan.\nGaris bergelombang mendominasi langit dan lanskap, menulari seluruh lingkungan dengan kecemasan.\n\nJembatan membentang dalam perspektif paksa, figur kerangka membawa tangan ke wajah dan menjerit tanpa suara.\nIkon tertinggi kecemasan eksistensial, lahir dari serangan panik nyata yang dialami Munch.` },
  'munch-madonna': { description: `Garis sinuosa dan aura gelap Madonna telah diterapkan.\nGelombang kemerahan yang menyelimuti tubuh telanjang mengekspresikan sensualitas mistis.\n\nLingkaran cahaya bukan sakral melainkan sensual, garis sinuosa membangkitkan ekstasi dan agoni sekaligus.\nKarya di mana Munch meleburkan kesucian dan kefanaan, menantang segala konvensi.` },
  'munch-puberty': { description: `Kerentanan yang terekspos dan bayangan mengancam Pubertas telah diterapkan.\nRemaja telanjang duduk di tempat tidur menatap penonton dengan ketakutan dan kepolosan.\n\nBayangan gelap di belakangnya menjulang sebagai kehadiran mengancam, mewujudkan kecemasan tumbuh dewasa.\nSalah satu karya pertama yang menangkap teror diam dari transisi masa kanak-kanak ke dewasa.` },
  'matisse-dance': { description: `Figur ritmis dan warna primer berani Tarian telah diterapkan.\nTubuh merah menari dalam ruang minimal biru dan hijau dengan energi primordial.\n\nLima figur membentuk lingkaran gerakan murni, disederhanakan hingga gestur esensial.\nPernyataan Matisse bahwa warna adalah ritme dan garis adalah emosi.` },
  'matisse-redroom': { description: `Bidang warna total dan pola dekoratif Kamar Merah telah diterapkan.\nSatu warna merah mendominasi ruang, melarutkan batas antara dinding dan meja.\n\nArabesque bunga berulang seperti wallpaper, menciptakan dunia datar dan melingkupi.\nKarya di mana Matisse membuktikan bahwa warna dapat menciptakan ruang tanpa perspektif.` },
  'matisse-hat': { description: `Warna wajah non-naturalistis dan sapuan kuas berani Wanita Bertopi telah diterapkan.\nHijau di hidung, ungu di dahi, oranye di leher — warna yang mengejutkan publik.\n\nKarya yang di Salon d'Automne 1905 memicu teriakan "Binatang buas!" dan membaptis Fauvisme.\nManifesto Matisse: warna tidak mendeskripsikan, melainkan mengekspresikan.` },
  'chagall-overthecity': { description: `Melayang dalam mimpi dan palet pastel Di Atas Kota telah diterapkan.\nPasangan kekasih melayang bebas di atas atap-atap desa, menantang gravitasi.\n\nAtap Vitebsk membentang di bawah dalam nada redup; di atas, Chagall dan Bella terbang dalam ekstasi warna.\nPernyataan paling murni bahwa cinta mampu membuat kita terbang.` },
  'chagall-iandthevillage': { description: `Multi-perspektif mimpi dan tumpang tindih kenangan Aku dan Desa telah diterapkan.\nWajah manusia hijau dan kambing putih saling menatap; di dalam kambing muncul adegan pemerahan susu.\n\nAtap terbalik, figur melayang, dan adegan simultan merajut memori dan mimpi.\nJendela ke masa kecil Chagall, di mana segalanya berbaur dalam mimpi tanpa gravitasi.` },
  'chagall-bouquet': { description: `Bunga cerah dan kekasih terbang Buket dengan Kekasih Terbang telah diterapkan.\nBuket bunga raksasa menyembur ke langit sementara kekasih melayang di antara kelopak.\n\nMerah, biru, kuning, dan hijau meledak bagai kembang api warna di atas latar gelap.\nKarya di mana Chagall merayakan cinta sebagai musim semi abadi yang melayang di udara.` },
  'picasso-demoiselles': { description: `Dekonstruksi radikal dan topeng Afrika Les Demoiselles d'Avignon telah diterapkan.\nLima tubuh terfragmentasi dalam sudut mustahil menghancurkan perspektif Renaisans.\n\nDua wajah di kanan, terinspirasi topeng Afrika, mengumumkan kelahiran Kubisme.\nDetonasi yang meresmikan seni abad ke-20, di mana representasi menyerah pada dekonstruksi.` },
  'picasso-guernica': { description: `Komposisi monumental dan chiaroscuro merobek Guernica telah diterapkan.\nSkala abu-abu, hitam dan putih — ketiadaan warna memperkuat horor perang.\n\nBanteng, kuda terluka, bola lampu, dan ibu dengan anak yang mati membentuk jeritan visual setinggi tiga setengah meter.\nTuntutan anti-perang paling kuat dalam sejarah seni, dilukis dalam enam minggu kemarahan.` },
  'picasso-doramaar': { description: `Multi-perspektif wajah dan warna psikologis Potret Dora Maar telah diterapkan.\nDepan dan samping berdampingan dalam satu wajah; warna mengekspresikan kondisi emosional, bukan penampilan nyata.\n\nMata asimetris, hidung bergeser, dan mulut tidak sejajar membangun potret kubis dengan intensitas psikologis.\nSintesis dekonstruksi kubis dan eksplorasi emosional dalam satu wajah.` },
  'frida-brokencolumn': { description: `Diseksi anatomis dan simbolisme mentah Kolom Patah telah diterapkan.\nTorso terbuka mengungkap kolom Ionik yang patah; paku menusuk kulit telanjang; air mata mengalir dari mata kering.\n\nKorset logam menopang tubuh yang runtuh, tetapi tatapannya tetap menantang.\nKarya paling visceral Frida, di mana rasa sakit menjadi peta tubuh dan pernyataan perlawanan.` },
  'frida-thornnecklace': { description: `Frontalitas ikonik dan simbologi alam Potret Diri dengan Kalung Duri dan Kolibri telah diterapkan.\nFrida menatap langsung penonton; duri mengelilingi lehernya seperti kalung rasa sakit, dan kolibri mati menggantung sebagai jimat.\n\nMonyet di bahu, kucing hitam mengintai — setiap elemen adalah simbol berkode dari penderitaannya.\nPotret diri yang menyintesiskan estetika Frida: alam Meksiko, rasa sakit, dan perlawanan.` },
  'frida-twofridaskahlo': { description: `Dualitas simbolis dan realisme emosional Dua Frida telah diterapkan.\nDua Frida duduk berdampingan, dihubungkan oleh arteri yang menyatukan jantung mereka yang terekspos.\n\nFrida Eropa bergaun putih berjantung patah dan berdarah; Frida Meksiko memegang potret Diego dan berjantung utuh.\nMahakarya keretakan batin, dilukis selama perceraian dari Diego Rivera.` },
  'lichtenstein-drowninggirl': { description: `Titik Ben-Day dan drama komik Drowning Girl telah diterapkan.\nTitik teratur menciptakan bayangan kulit; kontur hitam tebal mendefinisikan siluet emosional.\n\nSang protagonis berpikir: "Aku tak peduli... aku lebih suka tenggelam daripada minta tolong Brad!" — melodrama komik diangkat menjadi seni.\nKarya yang membuktikan bahwa satu panel komik dapat memuat seluruh intensitas seni.` },
  'lichtenstein-whaam': { description: `Ledakan grafis dan skala monumental Whaam! telah diterapkan.\nDua panel: pesawat menembak di kiri; ledakan titik dan garis meledak di kanan.\n\nOnomatope raksasa, garis kecepatan, dan bintang benturan mengubah perang menjadi tontonan pop.\nKarya ikonik Pop Art yang mengubah komik perang menjadi komentar budaya berskala besar.` },
  'lichtenstein-inthecar': { description: `Titik Ben-Day halus dan framing sinematik In the Car telah diterapkan.\nClose-up seperti frame film menampilkan dua wajah; teknik titik menciptakan bayangan dan nada kulit.\n\nPria dan wanita menatap arah yang sama tetapi tidak saling melihat; ketegangan sunyi lebih berbicara dari kata-kata.\nEsensi Pop Art di mana komik romantis menjadi refleksi tentang ketidakmampuan berkomunikasi.` },

  'vangogh_default': { description: `Gaya ekspresif Van Gogh dengan sapuan spiral dan warna intens telah diterapkan.\nSapuan kuas kuat dan terarah menciptakan tekstur bersemangat penuh energi emosional.\n\nKontras antara biru dalam dan kuning cerah mendefinisikan palet seniman yang melukis dengan hati.\nGaya tak salah lagi di mana setiap goresan mengungkap jiwa yang tersiksa dan penuh gairah.` },
  'klimt_default': { description: `Gaya dekoratif Klimt dengan lembaran emas dan pola geometris telah diterapkan.\nMosaik emas dan spiral ornamental menciptakan dunia kemewahan sensual.\n\nFigur datar terbungkus pola di mana yang organik dan geometris berkelindan.\nEstetika Sezession Wina, di mana dekorasi menjadi ekspresi jiwa.` },
  'munch_default': { description: `Gaya ekspresionis Munch dengan warna mengganggu dan bentuk bergelombang telah diterapkan.\nGaris sinuosa dan nada pucat menyampaikan kecemasan psikologis secara langsung.\n\nLanskap yang terdistorsi mengikuti ritme emosi internal, di mana tidak ada yang stabil.\nBahasa visual kecemasan, pelopor dalam mengubah isi jiwa menjadi gambar.` },
  'matisse_default': { description: `Gaya fauvis Matisse dengan warna murni dan bentuk sederhana telah diterapkan.\nWarna primer berani disusun tanpa menghormati kenyataan, dan bentuk direduksi ke esensi.\n\nGaris menjadi tarian dan warna menjadi musik — setiap elemen bernyanyi dengan kemandiriannya.\nSeni kegembiraan murni, di mana warna bebas dari segala kewajiban deskriptif.` },
  'chagall_default': { description: `Gaya mimpi Chagall dengan warna pastel dan figur melayang telah diterapkan.\nKekasih, hewan, dan atap melayang dalam ruang tanpa gravitasi, diwarnai nostalgia.\n\nMerah muda, ungu, dan biru melebur bagaikan kenangan yang berbaur dalam mimpi.\nDunia di mana cinta dan memori menantang hukum fisika dan waktu.` },
  'picasso_default': { description: `Gaya kubis Picasso dengan bentuk geometris dan perspektif ganda telah diterapkan.\nWajah dan tubuh terfragmentasi menjadi bidang bersudut, menampilkan beberapa sudut pandang secara bersamaan.\n\nGaris berani dan warna kontras membangun kenyataan yang didekonstruksi dan dirangkai ulang.\nRevolusi visual yang menghancurkan 500 tahun perspektif tradisional.` },
  'frida_default': { description: `Gaya simbolis Frida dengan warna Meksiko dan tatapan frontal intens telah diterapkan.\nMerah, hijau, dan kuning tradisi Meksiko membingkai ikonografi yang sangat personal.\n\nSetiap elemen — duri, hewan, tanaman — adalah simbol berkode dari rasa sakit, perlawanan, dan cinta.\nSeni pengakuan di mana tubuh yang patah menjadi wilayah identitas dan perjuangan.` },
  'lichtenstein_default': { description: `Gaya Pop Art Lichtenstein dengan titik Ben-Day dan kontur tebal telah diterapkan.\nPola titik teratur dan warna primer datar mengubah estetika komik menjadi seni.\n\nHitam, merah, biru, dan kuning dalam komposisi grafis yang mempertanyakan apa itu seni dan apa itu budaya populer.\nEsensi Pop Art yang menghapus batas antara museum dan budaya massa.` }
};

export default { mastersBasicInfo, mastersLoadingEducation, mastersResultEducation };
